### ISSUE TITLE
Label error in the template

### ISSUE THREAD

**Issue by MrBurnst** [viko18/JunaChimp#1]
Hi!

It looks like the labels 36,Frontal_Operculum,Frontal Lobe,L.FrOP and 35,Frontal_Operculum,Frontal Lobe,R.FrOP are switched. 36 is in the right hemisphere in Davi130_05mm.nii.gz

**Comment by MrBurnst** [comment]
... and also labels 37 & 38

**Comment by viko18** [comment]
Thanks for pointing this out. 

The label numbers are correct (odd = left, even = right) but the csv is wrong. I have added the correct csv file here (https://github.com/viko18/JunaChimp/blob/master/age_asym/Davi130.csv). The download zip on the web viewer files will be updated soon after resubmission of the manuscript following reviewer comments.
